# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/lcf15980849273/personalSpec.git'
target 'gittest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for gittest
  pod 'CFTimer'
  pod 'Protobuf'
  target 'gittestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'gittestUITests' do
    # Pods for testing
  end

end
